---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Hello World function using SAM template'

Resources:
  Hello:
    Type: AWS::Serverless::Function
    Properties:
      Handler: hello.handler
      Runtime: nodejs6.10
      Events:
        GetHello:
          Type: Api
          Properties:
            Path: /
            Method: get
